server:
    port: 8081
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/car_catalog_spring
        username: test
        password: test
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher